namespace TerminalVelocity.VT
{
    // https://en.wikipedia.org/wiki/C0_and_C1_control_codes
    public enum VTControlCode : byte
    {
        // C0
        Null = 0x00,
        StartOfHeading = 0x01,
        StartOfText = 0x02,
        EndOfText = 0x03,
        EndOfTransmission = 0x04,
        Enquiry = 0x05,
        Acknowledge = 0x06,
        Bell = 0x07,
        Alert = Bell,
        Backspace = 0x08,
        CharacterTabulation = 0x09,
        HorizontalTabulation = CharacterTabulation,
        LineFeed = 0x0A,
        LineTabulation = 0x0B,
        VerticalTabulation = LineTabulation,
        FormFeed = 0x0C,
        CarriageReturn = 0x0D,
        ShiftOut = 0x0E,
        ShiftIn = 0x0F,
        DataLinkEscape = 0x10,
        DeviceControlOne = 0x11,
        DeviceControlTwo = 0x12,
        DeviceControlThree = 0x13,
        DeviceControlFour = 0x14,
        NegativeAcknowledge = 0x15,
        SynchronousIdle = 0x16,
        EndOfTranmissionBlock = 0x17,
        Cancel = 0x18,
        EndOfMedium = 0x19,
        Substitute = 0x1A,
        Escape = 0x1B,
        FileSeparator = 0x1C,
        GroupSeparator = 0x1D,
        RecordSeparator = 0x1E,
        UnitSeparator = 0x1F,
        Space = 0x20,
        Del = 0x7F,

        // C1
        PaddingCharacter = 0x80,
        HighOctetPreset = 0x81,
        BreakPermittedHere = 0x82,
        NoBreakHere = 0x83,
        Index = 0x84,
        NextLine = 0x85,
        StartOfSelectedArea = 0x86,
        EndOfSelectedArea = 0x87,
        CharacterTabulationSet = 0x88,
        HorizontalTabulationSet = CharacterTabulationSet,
        CharacterTabulationWithJustification = 0x89,
        HorizontalTabulationWithJustification = CharacterTabulationWithJustification,
        LineTabulationSet = 0x8A,
        VerticalTabulationSet = LineTabulationSet,
        PartialLineForward = 0x8B,
        PartialLineDown = PartialLineForward,
        PartialLineBackward = 0x8C,
        PartialLineUp = PartialLineBackward,
        ReverseLineFeed = 0x8D,
        ReverseIndex = ReverseLineFeed,
        SingleShift2 = 0x8E,
        SingleShift3 = 0x8F,
        DeviceControlString = 0x90,
        PrivateUse1 = 0x91,
        PrivateUse2 = 0x92,
        SetTranmissionState = 0x93,
        CancelCharacter = 0x94,
        MessageWaiting = 0x95,
        StartOfProtectedArea = 0x96,
        EndOfProtectedArea = 0x97,
        StartOfString = 0x98,
        SingleGraphicCharacterIntroducer = 0x99,
        SingleCharacterIntroducer = 0x9A,
        ControlSequenceInitiator = 0x9B,
        StringTerminator = 0x9C,
        OperatingSystemCommand = 0x9D,
        PrivacyMessage = 0x9E,
        ApplicationProgramCommand = 0x9F
    }
}